config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tasks#index"
  
	resources :tasks do
		resources :subtasks do

			end

	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base

	belongs_to :task
	default_scope -> { order(created_at: :desc) }
	
end

app/models/task.rb
class Task < ActiveRecord::Base

	has_many :subtasks
	validates :priority, presence: true
	validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController

	before_action :set_task

	def index
		@subtasks = Subtask.all
	end

	def create
		subtask_params = params.require(:description).permit(:description, :due, :priority)
		task.subtasks.create(subtask_params)
		redirect_to task_path(id: task.id)
	end

	def complete
		@subtask.update_attribute(:completed_at, Time.now)
		redirect_to "tasks#index"
	end

	def destroy
		@subtask = @task.subtasks.find(params[:id])
		if @subtask.destroy
			flash[:sucess] = "Steps deleted"
		else
			flash[:error] = "Not comepleted"
		end
		redirect_to task_subtask_path
	end

	private

	def set_task
		@task = Task.find(params[:task_id])
	end

	def subtask_params
		params[:subtask].permit(:description)
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index
		@tasks = Task.all
	end

	def new
		@task = Task.new
	end

	def create
		task_params = params[:task].permit(:description, :priority, :due)
		@task = Task.new(task_params)
		if @task.save
			redirect_to task_path(id: @task.id)
		else
			render :new
		end
	end

	def show
		@task = Task.find(params[:id])
		@subtask = Subtask.new
	end

	def edit
		@task = Task.find(params[:id])
	end

	def update
		task_params = params[:task].permit(:description, :priority)
		@task = Task.find(params[:id])
		if @task.update(task_params)
			redirect_to tasks_path
		else
			render :view
		end
		
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to tasks_path
	end

	def complete
		@task = Task.find(params[:id])
		@task.update_attribute(:progress, "Completed")
		redirect_to task_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_files_helper.rb
module TasksFilesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subtasks/_form.html.erb
<%= form_for([@task_id, @task.subtasks.build]) do |f| %>
	
	<%= f.text_field :description, placeholder: "New Goals" %>
	<%= f.submit %>

<% end %>

app/views/subtasks/_subtask.html.erb
<p><%= subtask.description %></p>

<%= link_to "Delete", task_subtasks_path(@task, subtask.id), :class => 'btn btn-success', method: :delete, data: { confirm: "Are you sure?"} %>

<%= link_to "Mark as completed", complete_task_subtask_path(@task, subtask.id), method: :patch %>

app/views/subtasks/new.html.erb
<%= form_for @subtask, url: task_subtasks_path(task_id: @task_id), method: :post do |f| %>
	
	<div class="container">
		
		<div><h1>Your <strong>Small</strong> Tasks</h1></div>

		<div><%= f.text_area :description, size: "150x10" %></div>

		<div><%= select_date Date.today, prefix: :due %></div>
	
		<div class="container">
			
			<div class="radio">
				<%= f.radio_button(:priority, "High") %>
				<%= f.label(:priority, "High") %>
			</div>
			
			<div class="radio">
				<%= f.radio_button(:priority, "Medium") %>
				<%= f.label(:priority, "Medium") %>
			</div>

			<div class="radio">
				<%= f.radio_button(:priority, "Low") %>
				<%= f.label(:priority, "Low") %>
			</div>

		</div>
		
		<div>
			<%= f.submit "Let's do this", class: "btn btn-primary btn-lg btn-block" %>
		</div>

	</div>
<% end %>

app/views/tasks/edit.html.erb
<%= form_for @task, url: task_path(id: @task.id), method: :patch do |f| %>

	<div class="container">
		<div><h1>Your <strong>Goals</strong> </h1></div>
		<div><%= f.text_area :description%></div>
		<div><%= f.submit "Submit" %></div>
		
	</div>


<% end %>

app/views/tasks/index.html.erb
<div class="container">
	
<table class="table table-stripped">
	<thead>
		<th>Goals</th>

		<th>Buttons</th>

		<th>History</th>

		<th>Priority</th>

		<th>Progress</th>

	</thead>
		
		<% @tasks.each do |task|%>
	
	<tbody>

		<tr>
			<td><%= task.description %></td>

			<td>
					<%= link_to 'View', task_path(id: task.id), :class => 'btn btn-primary' %>

					<%= link_to 'Edit', edit_task_path(id: task.id), :class => 'btn btn-primary' %>

					<%= link_to 'Delete', task_path(id: task.id), :class => 'btn btn-success',
					method: :delete,
					data: { confirm: 'Are you sure you comepleted?' } %>

			</td>
		
			<td><%= task.created_at.strftime("Created at %m/%d/%Y")%> <br> <%=task.updated_at.strftime("Updated at %m/%d/%Y")%></td>
			
			<td> <%= task.priority %> </td>	

			<td> <%= task.progress %> </td>
		</tr>


		<% end %>
	</tbody>

</table>


	<%= link_to 'Set goals', new_task_path, :class => 'btn btn-info' %>


</div>

app/views/tasks/new.html.erb
<%= form_for @task, url: tasks_path, method: :post do |f| %>
	
	<div class="container">
		
		<div><h1>Your <strong>Goals</strong> </h1></div>

		<div><%= f.text_area :description, size: "150x10" %></div>

		<div>
			<%= f.label :due %>
			<%= select_date Date.today, prefix: :start_date  %>
		</div>

		<div class="container">
			
			<div class="radio">
				<%= f.radio_button(:priority, "High") %>
				<%= f.label(:priority, "High") %>
			</div>
			
			<div class="radio">
				<%= f.radio_button(:priority, "Medium") %>
				<%= f.label(:priority, "Medium") %>
			</div>

			<div class="radio">
				<%= f.radio_button(:priority, "Low") %>
				<%= f.label(:priority, "Low") %>
			</div>

		</div>
		
		<div>
			<%= f.submit "Let's do this", class: "btn btn-primary btn-lg btn-block" %>
		
		</div>
	</div>
	
<% end %>

app/views/tasks/show.html.erb
<div class="container">
	
	<h3> Your task : </h3>

		<p><%= @task.description %></p>

	<h3> And it's due on : </h3>

		<p><%= @task.due %></p>

	<h3> Your progress : </h3>

	<p><%= @task.progress %></p>


	<%= link_to 'edit', edit_task_path(id: @task.id) %>
	
</div>

app/views/tasks/view.html.erb
<h1>Show</h1>

<h2> <%= @task.priority %> </h2>

<p> <%= @task.description %> </p>

<p> <%= @task.priority %> </p>

<%= link_to 'edit', edit_post_path(id: @post.id) %>